
# STYLES
BG_COLOR_LIGHT = "#ebebeb"
BG_COLOR_DARK = "#242424"
MESSAGE_COLOR_LIGHT = "#b4b4b4"
MESSAGE_COLOR_DARK = "#3c3c3c"
ERROR_COLOR_LIGHT = "#dc2626"
ERROR_COLOR_DARK = "#dc2626"
SUCCESS_COLOR_LIGHT = "#11a37f"
SUCCESS_COLOR_DARK = "#11a37f"
ACCENT_COLOR_LIGHT = "#3b82f6"
ACCENT_COLOR_DARK = "#3b82f6"

# PATHS
IMAGES_PATH = "imgs"
SOUNDS_PATH = "sounds"
